# Generated by Django 3.1.4 on 2021-11-13 10:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OuvrageInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID pour cette version dans toute la biliothèque', primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=100, verbose_name='Auteur')),
                ('name', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('publish_date', models.DateField(verbose_name='Date de Publication')),
                ('borrowable', models.BooleanField(default=True)),
                ('ref_type', models.CharField(choices=[('BK', 'Livre'), ('RV', 'Revue'), ('CD', 'CD'), ('BD', 'BD'), ('DVD', 'DVD')], default='BK', help_text='Type ouvrage', max_length=3)),
            ],
            options={
                'verbose_name': 'Ouvrage',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('social_status', models.CharField(choices=[('CH', 'Chômeur'), ('ET', 'Étudiant'), ('SR', 'Senior'), ('ML', 'Militaire'), ('AU', 'Autre')], default='AU', max_length=2)),
                ('first_name', models.CharField(default='first_name', max_length=60)),
                ('last_name', models.CharField(default='last_name', max_length=60)),
                ('balance', models.IntegerField(default=0, verbose_name='Solde €')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Utilisateur',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginning_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de début')),
                ('ending_date', models.DateField(default=datetime.datetime(2022, 11, 12, 10, 16, 31, 619792, tzinfo=utc), verbose_name='Date de fin')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='library_app.user', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Abonnement',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginning_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de début')),
                ('ending_date', models.DateField(default=datetime.datetime(2021, 12, 13, 10, 16, 31, 619792, tzinfo=utc), verbose_name='Date de fin')),
                ('returned', models.BooleanField(default=False, verbose_name='Retourné ?')),
                ('reference', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='library_app.ouvrageinstance', verbose_name='Ouvrage')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='library_app.user', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Emprunt',
            },
        ),
        migrations.CreateModel(
            name='Bad_borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ending_date', models.DateField(default=datetime.datetime(2023, 10, 21, 10, 16, 31, 620792, tzinfo=utc), verbose_name='Date de fin')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='library_app.user', verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Mauvais utilisateur',
            },
        ),
    ]
