# Generated by Django 3.1.4 on 2021-11-13 11:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_auto_20211113_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bad_borrower',
            name='ending_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 21, 11, 49, 15, 39570, tzinfo=utc), verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='ending_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 13, 11, 49, 15, 39570, tzinfo=utc), verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='ending_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 12, 11, 49, 15, 39570, tzinfo=utc), verbose_name='Date de fin'),
        ),
    ]
