# Generated by Django 3.1.4 on 2021-11-13 12:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0009_auto_20211113_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bad_borrower',
            name='ending_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 21, 12, 23, 42, 36204, tzinfo=utc), verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='ending_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 13, 12, 23, 42, 36204, tzinfo=utc), verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='ouvrageinstance',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='ending_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 12, 12, 23, 42, 36204, tzinfo=utc), verbose_name='Date de fin'),
        ),
    ]
