# Generated by Django 3.1.4 on 2021-11-13 22:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0012_auto_20211113_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bad_borrower',
            name='ending_date',
            field=models.DateField(default=datetime.datetime(2023, 10, 21, 22, 7, 8, 648133, tzinfo=utc), verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='ending_date',
            field=models.DateField(default=datetime.datetime(2021, 12, 13, 22, 7, 8, 648133, tzinfo=utc), verbose_name='Date de fin'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='ending_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 12, 22, 7, 8, 647134, tzinfo=utc), verbose_name='Date de fin'),
        ),
    ]
